### ISSUE TITLE
ERR_UNSUPPORTED_PROTOCOL for client in helia-lan-discovery

### ISSUE THREAD

**Issue by macterra** [ipfs-examples/helia-examples#296]
using Node.js v20.11.1

`npm run client` fails with this error:

```
file:///home/david/self/helia-examples/node_modules/@libp2p/multistream-select/dist/src/select.js:95
    throw new CodeError('protocol selection failed', 'ERR_UNSUPPORTED_PROTOCOL');
          ^

CodeError: protocol selection failed
    at Module.select (file:///home/david/self/helia-examples/node_modules/@libp2p/multistream-select/dist/src/select.js:95:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionImpl.newStream [as _newStream] (file:///home/david/self/helia-examples/node_modules/libp2p/dist/src/upgrader.js:330:50)
    at async ConnectionImpl.newStream (file:///home/david/self/helia-examples/node_modules/libp2p/dist/src/connection/index.js:94:24) {
  code: 'ERR_UNSUPPORTED_PROTOCOL',
  props: {}
}
```

I'm running `npm run server` in another terminal on the same machine.

**Comment by achingbrain** [comment]
I can't replicate this problem, and the example is [passing CI](https://github.com/ipfs-examples/helia-examples/actions/runs/11234289987/job/31229802410).

Please re-open if you're still seeing this issue.
